### ISSUE TITLE
Wrong parameter names for Cura

### ISSUE THREAD

**Issue by Ralf-W** [sclebo05/KobraNeoProfiles#8] opened 2023-04-10 18:17 UTC
Thanks a lot for your excellent KobraNeoProfiles! They work very good with my printer. 

Yet, the 'GCode start sequence' in KobraNeoGcodes.txt does not work as expected. It calls parameters by names Cura does not understand. https://community.ultimaker.com/topic/18559-changing-cura-generated-start-code/page/3/ 

Result:
- The values of [first_layer_temperature] and  [first_layer_height] are ignored. Cura does use default values instead.
- The printer stays at z=2.0mm for the first intro line and is forced down to a fixed value of z=0.3mm while drawing the second intro line.

I corrected this misbehaviour, and tested it successfully as follows:

1) Exchange [first_layer_temperature] by {material_print_temperature_layer_0}.
2) Exchange [first_layer_height] by {layer_height_0}.
3) For the end of the second line exchange Z0.3[first_layer_height] by Z{layer_height_0}.
4) Add heating the bed to the desired {material_bed_temperature_layer_0}.

Here is my working startup sequence:

; Add these codes to the start and end sections of the Printer settings
; In Cura navigate to Settings -> Printers -> Manage Printers and you will find Machine Settings. 
; The below start and end sections can be pasted into the corresponding boxes.

; start gcode
G21 ;metric values
G90 ;absolute positioning
M82 ;set extruder to absolute mode (redundant command)
M107 ;start with the fan off
M117 Homing X/Y ...
G28 X0 Y0 ;move X/Y to min endstops
M117 Homing Z ...
G28 Z0 ;move Z to min endstops
G1 Z15.0 F240 ;move the platform down 15mm
M117 Heating ...
M140 S{material_bed_temperature_layer_0} ;Start heating bed
M105 ;measure and display temperature of bed and nozzle
M190 S{material_bed_temperature_layer_0} ;Wait for bed to reach temp before proceeding
M104 S{material_print_temperature_layer_0} ;Start heating extruder
M105 ;measure and display temperature of bed and nozzle
M109 S{material_print_temperature_layer_0} ;Wait for extruder to reach temp before proceeding
M117 Start cleaning ...
M420 S1 ; Enable Bed Levelling Mesh
G92 E0 ;zero the extruded length
M413 S0 ; disable power loss recovery - may reduce blobbing and avoid unexpected recovery
; M500 ; store eeprom settings
M117 Intro line ...
G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
G1 X0.1 Y20 Z{layer_height_0} F5000.0 ; Move to start position
G1 X0.1 Y200.0 Z{layer_height_0} F1500.0 E15 ; Draw the first line
G1 X0.4 Y200.0 Z{layer_height_0} F5000.0 ; Move to side a little
G1 X0.4 Y20 Z{layer_height_0} F1500.0 E30 ; Draw the second line
G92 E0 ; Reset Extruder
G1 X5 Y20 Z0.3 F240 ; Move over to prevent blob squish
G92 E0 ; Reset Extruder
M420 S1 ; Enable Bed Levelling Mesh
M117 Printing...
;------------------------

**Comment by sclebo05** [comment] 2023-04-11 14:09
Thanks for the in-depth feedback. I've been away from Cura for a long time, and I never noticed that the temps weren't responding as intended - it did the fallback and worked so I moved on.

I've split the Gcode files into Cura and Prusa flavors. I've added your heat/layer tweaks for Cura and also played with speeds and verbiage within the file.  It was probably good to revisit these. thanks!

**Comment by Ralf-W** [comment] 2023-04-11 19:20
Thanks!

**Comment by sclebo05** [comment] 2023-04-13 12:00
Closing as resolved.

**Closed as completed by sclebo05** 2023-04-13 12:00 UTC
